version: '2.7'

rpc:
    listen: tcp://0.0.0.0:6001

logs:
    level: debug

server:
    command: "php app.php"
    relay: pipes

temporal:
    address: temporal:7233
    activities:
        num_workers: 5

jobs:
    consume: [ "test" ]
    pipelines:
        test:
            driver: memory
            config:
                priority: 10
                prefetch: 10

grpc:
    listen: "tcp://0.0.0.0:9000"
    proto:
        - "./proto/api/cinema/v1/service.proto"

centrifuge:
    grpc_api_address: "centrifugo:10000"
    version: "1.0.0"

metrics:
    address: 0.0.0.0:2112
